name: Build and Commit DLL

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # 자동 푸시 권한용

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish DLL
        run: dotnet publish -c Release -o output/

      - name: Copy DLL to Plugins folder
        run: |
          mkdir -p Assets/Plugins
          cp output/*.dll Assets/Plugins/

      - name: Commit and Push DLL
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Assets/Plugins/*.dll
          git commit -m "chore: update DLL [skip ci]" || echo "No changes to commit"
          git push
