name: Build DLL

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: write  # push 권한 확보

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. 레포 체크아웃
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. .NET 설치
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # 3. 의존성 복원
      - name: Restore dependencies
        run: dotnet restore

      # 4. 빌드
      - name: Build project
        run: dotnet build --configuration Release

      # 5. DLL 생성
      - name: Publish DLL
        run: dotnet publish -c Release -o output/

      # 6. DLL 복사 (PowerShell 호환)
      - name: Copy DLL to Plugins folder
        shell: pwsh
        run: |
          if (-Not (Test-Path -Path runtime/Plugins)) {
            New-Item -ItemType Directory -Path runtime/Plugins
          }
          Copy-Item -Path output\*.dll -Destination runtime/Plugins -Force

      # 7. 커밋 & 강제 푸시
      - name: Commit and Push DLL
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add runtime/Plugins/PJHUtilLibrary.dll
          git commit -m "chore: update DLL [skip ci]" || Write-Host "No changes to commit"
          git push --force origin HEAD:main
